//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipGateVirtualFaxGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SipGateVirtualFaxGui.Properties.Resources.de", typeof(Resources_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipgate Virtuelles Fax.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd. MM. yyyy HH:mm:ss.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Sipgate Zugangsdaten namens &quot;{0}&quot; konnten nicht gefunden werden!.
        /// </summary>
        public static string Err_CredentialsNotFound {
            get {
                return ResourceManager.GetString("Err_CredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Faxleitungen konnten nicht von Sipgate geladen werden!.
        /// </summary>
        public static string Err_FailedToLoadFaxlines {
            get {
                return ResourceManager.GetString("Err_FailedToLoadFaxlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Dokument konnte nicht geöffnet werden!.
        /// </summary>
        public static string Err_FailedToOpenDocument {
            get {
                return ResourceManager.GetString("Err_FailedToOpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Senden des Fax ist fehlgeschlagen!.
        /// </summary>
        public static string Err_FailedToSendFax {
            get {
                return ResourceManager.GetString("Err_FailedToSendFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Scannen ist fehlgeschlagen!.
        /// </summary>
        public static string Err_ScanningFailed {
            get {
                return ResourceManager.GetString("Err_ScanningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faxleitung.
        /// </summary>
        public static string Label_Faxline {
            get {
                return ResourceManager.GetString("Label_Faxline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF öffnen.
        /// </summary>
        public static string Label_OpenPdf {
            get {
                return ResourceManager.GetString("Label_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empfänger.
        /// </summary>
        public static string Label_Recipient {
            get {
                return ResourceManager.GetString("Label_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erneut senden.
        /// </summary>
        public static string Label_Resend {
            get {
                return ResourceManager.GetString("Label_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ein Dokument scannen.
        /// </summary>
        public static string Label_ScanDocument {
            get {
                return ResourceManager.GetString("Label_ScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string Label_Scanner {
            get {
                return ResourceManager.GetString("Label_Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhandenes Dokument auswählen.
        /// </summary>
        public static string Label_SelectExistingDocument {
            get {
                return ResourceManager.GetString("Label_SelectExistingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Fax.
        /// </summary>
        public static string NewFax {
            get {
                return ResourceManager.GetString("NewFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein Dokument gescannt!.
        /// </summary>
        public static string NoDocumentScanned {
            get {
                return ResourceManager.GetString("NoDocumentScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Dokumente.
        /// </summary>
        public static string PdfDocuments {
            get {
                return ResourceManager.GetString("PdfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senden fehlgeschlagen.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartend.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sende.
        /// </summary>
        public static string Status_Sending {
            get {
                return ResourceManager.GetString("Status_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erfolgreich gesendet.
        /// </summary>
        public static string Status_SuccessfullySent {
            get {
                return ResourceManager.GetString("Status_SuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannter Zustand.
        /// </summary>
        public static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gib hier die Empfängerfaxnummer ein. Die Nummer muss mindests eine regionale Vorwahl enthalten..
        /// </summary>
        public static string Toolbox_RecipientInput {
            get {
                return ResourceManager.GetString("Toolbox_RecipientInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be&amp;enden.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffnen.
        /// </summary>
        public static string Tray_Open {
            get {
                return ResourceManager.GetString("Tray_Open", resourceCulture);
            }
        }
    }
}
