//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipGateVirtualFaxGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SipGateVirtualFaxGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sipgate Virtual Fax.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy HH:mm:ss.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the Sipgate credentials named &quot;{0}&quot;!.
        /// </summary>
        public static string Err_CredentialsNotFound {
            get {
                return ResourceManager.GetString("Err_CredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Faxlines from Sipgate!.
        /// </summary>
        public static string Err_FailedToLoadFaxlines {
            get {
                return ResourceManager.GetString("Err_FailedToLoadFaxlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the docuement!.
        /// </summary>
        public static string Err_FailedToOpenDocument {
            get {
                return ResourceManager.GetString("Err_FailedToOpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send fax!.
        /// </summary>
        public static string Err_FailedToSendFax {
            get {
                return ResourceManager.GetString("Err_FailedToSendFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scanning failed!.
        /// </summary>
        public static string Err_ScanningFailed {
            get {
                return ResourceManager.GetString("Err_ScanningFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faxline.
        /// </summary>
        public static string Label_Faxline {
            get {
                return ResourceManager.GetString("Label_Faxline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open PDF.
        /// </summary>
        public static string Label_OpenPdf {
            get {
                return ResourceManager.GetString("Label_OpenPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient.
        /// </summary>
        public static string Label_Recipient {
            get {
                return ResourceManager.GetString("Label_Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Label_Resend {
            get {
                return ResourceManager.GetString("Label_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan a document.
        /// </summary>
        public static string Label_ScanDocument {
            get {
                return ResourceManager.GetString("Label_ScanDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanner.
        /// </summary>
        public static string Label_Scanner {
            get {
                return ResourceManager.GetString("Label_Scanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing document.
        /// </summary>
        public static string Label_SelectExistingDocument {
            get {
                return ResourceManager.GetString("Label_SelectExistingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Fax.
        /// </summary>
        public static string NewFax {
            get {
                return ResourceManager.GetString("NewFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document has been scanned!.
        /// </summary>
        public static string NoDocumentScanned {
            get {
                return ResourceManager.GetString("NoDocumentScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Documents.
        /// </summary>
        public static string PdfDocuments {
            get {
                return ResourceManager.GetString("PdfDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed.
        /// </summary>
        public static string Status_Failed {
            get {
                return ResourceManager.GetString("Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Status_Pending {
            get {
                return ResourceManager.GetString("Status_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending.
        /// </summary>
        public static string Status_Sending {
            get {
                return ResourceManager.GetString("Status_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully sent.
        /// </summary>
        public static string Status_SuccessfullySent {
            get {
                return ResourceManager.GetString("Status_SuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown State.
        /// </summary>
        public static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the recipient fax number here. The number requires at least a regional prefix..
        /// </summary>
        public static string Toolbox_RecipientInput {
            get {
                return ResourceManager.GetString("Toolbox_RecipientInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        public static string Tray_Open {
            get {
                return ResourceManager.GetString("Tray_Open", resourceCulture);
            }
        }
    }
}
