name: .NET Desktop

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore the application
      run: msbuild SipgateVirtualFax.sln /t:Restore /p:Configuration=Release

    - name: Build Solution
      run: msbuild SipgateVirtualFax.sln /p:Configuration=Release

    #- name: Build Installer
    #  run: |
    #    Start-Process -Wait -NoNewWindow -FilePath "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" -ArgumentList $env:Solution_Name, "/build", $env:Configuration, "Installer/Installer.vdproj" -WorkingDirectory .
    #  env:
    #    Configuration: ${{ matrix.configuration }}
